_BASE_: video_maskformer2_swin_large_IN21k_384_bs16_8ep.yaml
MODEL:
  WEIGHTS: "weights/model_final_e5f453.pkl"
  MASK_FORMER:
#    NUM_OBJECT_QUERIES: 150
    SUP_TYPE: "mask_projection_and_STpairwise"
    WEAK_SUPERVISION:
      PROJECTION_WEIGHT: 5.0
      PAIRWISE_WEIGHT: 2.0
      PAIRWISE:
        SIZE: 3
        DILATION: 2
        COLOR_THRESH: 0.3
        WARMUP_ITERS: 2000
  MASK_FORMER_VIDEO:
    WEAK_SUPERVISION:
      TEMPORAL_PAIRWISE_WEIGHT: 1.0
#    TEST:
#      TRACKER_TYPE: "minvis"
#      MERGE_ON_CPU: True
INPUT:
  DATASET_MAPPER_NAME: "video_instance_with_temp_coords"
  SAMPLING_FRAME_NUM: 3
  FIXED_SAMPLING_INTERVAL: True
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.00005
  STEPS: (8000,)
  MAX_ITER: 12000
  CHECKPOINT_PERIOD: 12000
TEST:
  EVAL_PERIOD: 0
  DETECTIONS_PER_IMAGE: 10
DATALOADER:
  NUM_WORKERS: 8