_BASE_: video_maskformer2_R50_bs16_8ep.yaml
MODEL:
  WEIGHTS: "weights/model_final_3c8ec9.pkl"
  MASK_FORMER:
    SUP_TYPE: "mask_projection_and_spatial_pairwise_and_temporal_pairwise"
    WEAK_SUPERVISION:
      PROJECTION_WEIGHT: 5.0
      PAIRWISE_WEIGHT: 2.0
      TEMPORAL_PAIRWISE_WEIGHT: 2.0
      PAIRWISE:
        SIZE: 3
        DILATION: 2
        COLOR_THRESH: 0.3
        WARMUP_ITERS: 4000  # 2000
#SOLVER:
#  IMS_PER_BATCH: 8  # 16
#  BASE_LR: 0.00005  # 0.0001
#  STEPS: (11000,)  # (5500,)
#  MAX_ITER: 16000  # 8000
#  CHECKPOINT_PERIOD: 4000  # 2000
#TEST:
#  EVAL_PERIOD: 2000  # 2000

SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.000025
  STEPS: (22000,)
  MAX_ITER: 32000
  CHECKPOINT_PERIOD: 8000
TEST:
  EVAL_PERIOD: 4000