_BASE_: video_maskformer2_R50_bs16_8ep.yaml
MODEL:
  WEIGHTS: "weights/model_final_3c8ec9.pkl"
  MASK_FORMER:
    SUP_TYPE: "mask_projection_and_pairwise"
    WEAK_SUPERVISION:
      PROJECTION_WEIGHT: 5.0
      PAIRWISE_WEIGHT: 2.0
      PAIRWISE:
        SIZE: 3
        DILATION: 2
        COLOR_THRESH: 0.3
        WARMUP_ITERS: 4000
  MASK_FORMER_VIDEO:
    TEST:
      TRACKER_TYPE: "minvis"
      MERGE_ON_CPU: True